name: Facebook Scheduler

# limit the permission to only read the github repo
permissions:
  contents: read

on:
  schedule:
    - cron: "0 0 25 * *" # midnight UTC every 25th day of the month

jobs:
  trigger-test-arps:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Facebook Scheduler
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"integrationKey\":\"${{ secrets.INTEGRATION_KEY }}\"}" \
            "${{ secrets.TEST_SITE_URL }}/.netlify/functions/facebookScheduler"
