name: Instagram Scheduler

# limit the permission to only read the github repo
permissions:
  contents: read

on:
  schedule:
    - cron: "0 12 * * *" # every day at 12:00 AM UTC
    - cron: "20 3 * * *" # every day at 03:20 AM UTC

jobs:
  trigger-instagramScheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Instagram Scheduler
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"integrationKey\":\"${{ secrets.INTEGRATION_KEY }}\"}" \
            "${{ secrets.TEST_SITE_URL }}/.netlify/functions/instagramScheduler"
