name: Instagram Scheduler

# limit the permission to only read the github repo
permissions:
  contents: read

on:
  schedule:
    - cron: "0 9 * * *" # every day at 9 AM UTC
    - cron: "0 2 * * *" # every day at 2 PM UTC

jobs:
  trigger-test-arps:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Instagram Scheduler
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"integrationKey\":\"${{ secrets.INTEGRATION_KEY }}\"}" \
            "${{ secrets.TEST_SITE_URL }}/.netlify/functions/instagramScheduler"
